# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#Environment Settings
. ~/.shell_startup/environment

#Aliases
. ~/.shell_startup/aliases

#Common Shell Startup
. ~/.shell_startup/shell

#
# Start Bash Options
#

# append to the history file, don't overwrite it
shopt -s histappend

# resize window after each command if reqd,
# updates the values of LINES and COLUMNS.
shopt -s checkwinsize

PROMPT_COMMAND='history -a'

if [ $__custom_var_os == "Darwin" ]
then
	if [ -f /sw/etc/bash_completion ]
	then
   		. /sw/etc/bash_completion
	fi
fi

if [ $__custom_var_os == "Linux" ]
then
	if [ -f /etc/bash_completion ] && ! shopt -oq posix 
	then
    		. /etc/bash_completion
	fi
fi

#
# End Bash Options
#

. ~/.shell_startup/eyecandy
