# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#Environment Settings
. ~/.shell_startup/environment

#Aliases
. ~/.shell_startup/aliases

#
# Start Bash Options
#

#vi mode in shell
set -o vi

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

PROMPT_COMMAND='history -a'
INPUTRC=~/.inputrc

if [ $__custom_var_os == "Darwin" ]
then
	if [ -f /sw/etc/bash_completion ]
	then
   		. /sw/etc/bash_completion
	fi
fi

if [ $__custom_var_os == "Linux" ]
then
	if [ -f /etc/bash_completion ] && ! shopt -oq posix 
	then
    		. /etc/bash_completion
	fi
fi

#
# End Bash Options
#

. ~/.shell_startup/eyecandy
