runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

syntax on
syntax enable

set vb
set number
set ruler
set hlsearch 
set ignorecase
set nocompatible

set modelines=1 " Not a good idea; see CVE-2007-2438

set bs=indent,eol,start
set tabstop=4
set shiftwidth=4
set expandtab

set textwidth=120
set formatoptions+=t
"set colorcolumn=120
"Highlight any lines longer than 120 chars
":2mat ErrorMsg '\%121v.'
":au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>120v.\+', -1)

filetype indent plugin on
set autoindent

set ff=unix
"se nobomb
"source ~/cscope_maps.vim
"highlight Normal ctermfg=darkgrey  ctermbg=black

source ~/.vim/dhexception.vim
source ~/.vim/python.vim

au FileType ruby setl sw=2 sts=2

augroup filetypedetect 
  au BufNewFile,BufRead *.pig set filetype=pig syntax=pig 
  au BufNewFile,BufRead *.yaml set ts=2
augroup END

"NERDTree
"Open NERDTree on start
"autocmd VimEnter * NERDTree
"Focus on file when opened with NERDTree
autocmd VimEnter * wincmd p
"Open NERDTree on start even with no input files
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
"Close vim if only NERDTree window is open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif


"Airline
let g:airline_theme='dark'

"Solarized
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

"Disable Background Color Erase
"Fpr Solarized inside tmux
set t_ut=

"add fzf path to runtimepath
set rtp+=/usr/local/opt/fzf

"ctags
set tags=$HOME/git/.tags
nnoremap <C-]> g<C-]>
" :tselect /pattern
" <C-T>
